/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        primary: {
          DEFAULT: "#010101",
          foreground: "#ffffff",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        "on-surface-variant": "#444748",
        "trend-down": "#FF4D4F",
        "on-primary": "#ffffff",
        "inverse-primary": "#c8c6c5",
        "accent-purple": "#E5ECF6",
        "on-tertiary": "#ffffff",
        "surface-card": "#FFFFFF",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed": "#1c1b1a",
        "surface-container-high": "#ebe7e6",
        "surface-container": "#f1edec",
        "surface-bright": "#fdf8f8",
        "surface-container-low": "#f7f3f2",
        "canvas-bg": "#F7F9FC",
        "error-container": "#ffdad6",
        "on-primary-container": "#858484",
        "accent-yellow": "#FFF3C4",
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#878482",
        "surface": "#fdf8f8",
        "secondary": "#415aa6",
        "accent-mint": "#BAEDBD",
        "on-tertiary-fixed-variant": "#484645",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e6e2df",
        "tertiary": "#010101",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "outline": "#747878",
        "tertiary-fixed-dim": "#cac6c4",
        "outline-variant": "#c4c7c7",
        "primary-container": "#1c1c1c",
        "primary-fixed": "#e5e2e1",
        "trend-up": "#4AA785",
        "inverse-on-surface": "#f4f0ef",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#1d1c1b",
        "on-surface": "#1c1b1b",
        "accent-blue": "#E3F5FF",
        "surface-dim": "#ddd9d8",
        "on-secondary-container": "#223f89",
        "on-secondary-fixed": "#00174c",
        "surface-container-highest": "#e5e2e1",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-fixed-variant": "#26428d",
        "surface-variant": "#e5e2e1",
        "secondary-container": "#95adff",
        "on-primary-fixed-variant": "#474746",
        "inverse-surface": "#313030",
        "surface-tint": "#5f5e5e",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#dbe1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "right-panel-width": "280px",
        "gutter": "24px",
        "sidebar-width": "240px",
        "margin-page": "32px",
        "card-padding": "24px",
        "sidebar-width-offset": "240px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "metric-lg": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "metric-lg": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "body-sm": ["11px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};

